removed azs:
- name: z1
  cpi: lab
  cloud_properties:
    datacenters:
    - clusters: [vSAN-Cluster: {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: mynetwork
  type: manual
  subnets:
  - range: 10.100.xx.xx/24
    gateway: 10.100.xx.xx
    reserved: [10.100.xx.xx-10.100.xx.xx, 10.100.155.xx, xx.100.xx.xx]
    static: [10.100.xx.xx-10.100.xx.xx]
    az: z1
    dns: [8.8.8.8]
    cloud_properties:
      name: vlan55

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: mynetwork
