cpis:
- name: lab
  type: vsphere
  properties:
    host: esxi ip
    user: "esxi user"
    password: esxi pwd
    datacenters:
    - clusters:
      - {vSAN-Cluster: {}}
      datastore_pattern: ^(datastore2|datastore3|datastoreSSD4|datastoreSSD5)$
      disk_path: my-bucc2-disk
      name: Datacenter
      persistent_datastore_pattern: ^(datastore2|datastore3|datastoreSSD4|datastoreSSD5)$
      template_folder: BUCC2_Templates
      vm_folder: BUCC2_VMs
